config/routes.rb
Rails.application.routes.draw do
  resources :candies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  root 'candies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candy.rb
class Candy < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/candies_controller.rb
class CandiesController < ApplicationController
  before_action :set_candy, only: [:show, :edit, :update, :destroy]

  # GET /candies
  # GET /candies.json
  def index
    @candies = Candy.all
  end

  # GET /candies/1
  # GET /candies/1.json
  def show
  end

  # GET /candies/new
  def new
    @candy = Candy.new
  end

  # GET /candies/1/edit
  def edit
  end

  # POST /candies
  # POST /candies.json
  def create
    @candy = Candy.new(candy_params)

    respond_to do |format|
      if @candy.save
        format.html { redirect_to @candy, notice: 'Candy was successfully created.' }
        format.json { render :show, status: :created, location: @candy }
      else
        format.html { render :new }
        format.json { render json: @candy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candies/1
  # PATCH/PUT /candies/1.json
  def update
    respond_to do |format|
      if @candy.update(candy_params)
        format.html { redirect_to @candy, notice: 'Candy was successfully updated.' }
        format.json { render :show, status: :ok, location: @candy }
      else
        format.html { render :edit }
        format.json { render json: @candy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candies/1
  # DELETE /candies/1.json
  def destroy
    @candy.destroy
    respond_to do |format|
      format.html { redirect_to candies_url, notice: 'Candy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candy
      @candy = Candy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candy_params
      params.require(:candy).permit(:name)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candies_helper.rb
module CandiesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/candies/_form.html.erb
<%= form_for(candy) do |f| %>
  <% if candy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candy.errors.count, "error") %> prohibited this candy from being saved:</h2>

      <ul>
      <% candy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name , class:"form-control" %>
  </div>

  <div class="actions">
    <%= f.submit :create, class:"btn btn-default"%>
  </div>
<% end %>

app/views/candies/edit.html.erb
<h1>Editing Candy</h1>

<%= render 'form', candy: @candy %>

<%= link_to 'Show', @candy , class:"btn btn-default" %> |
<%= link_to 'Back', candies_path , class:"btn btn-default"  %>

app/views/candies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Candies</h1>

<table class="table table-responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candies.each do |candy| %>
      <tr>
        <td><%= candy.name %></td>
        <td><%= link_to 'Show', candy , class:"btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_candy_path(candy) , class:"btn btn-success" %></td>
        <td><%= link_to 'Destroy', candy, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candy', new_candy_path , class:"btn btn-success" %>

app/views/candies/new.html.erb
<h1>New Candy</h1>

<%= render 'form', candy: @candy %>

<%= link_to 'Back', candies_path , class:"btn btn-xs btn-danger" %>

app/views/candies/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">

<div class="panel-heading">candy</div>

<div class="panel-body">


<p>
  <strong>Name:</strong>
  <%= @candy.name %>
</p>


</div>

<div class="panel-footer">

<%= link_to 'Edit', edit_candy_path(@candy) ,class:"btn btn-xs btn-danger" %> |
<%= link_to 'Back', candies_path , class:"btn btn-xs btn-danger" %>

</div></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab5</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body="container">
    <nav class="navbar navbar-inverse">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">lab5</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/">Candies</a></li>
      <li><a href="/static_pages/home">Home</a></li>
      <li><a href="/static_pages/help">Help</a></li>
      <li><a href="/static_pages/about">About</a></li>
    </ul>
</nav>
<div><%= yield %></div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>